model: lightgbm
n_splits: 5
num_boost_round: 20000
early_stopping_rounds: 500

params:
  objective: regression
  metric: rmse
  learning_rate: 0.01
  num_leaves: 31
  min_child_samples: 50
  feature_fraction: 0.7
  bagging_fraction: 0.7
  bagging_freq: 1
  reg_alpha: 1.0
  reg_lambda: 5.0
  verbose: -1
